# Inverse-Matrix issue with openblas on windows

In [10]:
import numpy as np

mat = np.array(
    [[0.524969497130176, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
     [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.9114215350130223, -1.0, 0.0, 0.0, 0.0, 0.0],
     [0.0, 0.0, 0.4994564583872562, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
     [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.9114215350130223, -1.0, 0.0, 0.0, 0.0, 0.0],
     [0.0, 0.0, 0.0, 0.0, 0.4157470351358414, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
     [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.9414610469335363, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.39900368017044757, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.9414610469335363, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4109228810609098, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, -0.981276502042976, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3389255065933183, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, -0.981276502042976, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.38662945932754733, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, -0.981276502042976, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.31231558385767905, 0.0, -0.3564172116110879, 0.0, -0.33126720453123293, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, -0.9276138423231451, -1.0, 0.0, 0.0], 
     [0.0, 0.0, 0.0, 0.0, -0.5027855206773494, 0.0, -0.49721447932265067, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, -0.9276138423231451, -1.0, 0.0, 0.0], 
     [-0.7992413362550559, 0.0, -0.20075866374494417, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, -0.9276138423231451, -1.0, 0.0, 0.0],
     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.15668367503565162, 0.0, -0.26103135518636406, 0.0, -0.5822849697779844, 0.0, 1.0, 0.0, 0.0, 0.0],
     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, -0.9282174988800027, -1.0],
     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 1.0, 0.0], 
     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]]
)

rhs = np.array([ 0.02872055, -0.06976937,  0.09336409, -0.06976937,  0.06331449,
       -0.17026268,  0.05900936, -0.17026268,  0.10914496, -0.25648999,
        0.08462169, -0.25648999,  0.10215808, -0.25648999,  0.52276802,
       -0.04372137,  0.36169883, -0.04372137,  0.15310011, -0.04372137,
        0.09426633, -0.04375107,  0.09426902,  0.        ])

## Openblas:

In [17]:
sol1 = np.linalg.solve(mat, rhs)
sol1

array([ 5.31017265e-02,  8.43763359e-04,  1.85242027e-01,  8.43763359e-04,
       -1.36163481e+00,  4.58202618e-01, -1.00047513e+00,  4.58202618e-01,
       -2.39628959e-01,  2.07613982e-01, -3.62888864e-01,  2.07613982e-01,
       -2.72757028e-01,  2.07613982e-01,  2.28232867e-01,  2.40144423e-01,
        4.12466215e-01,  2.40144423e-01, -1.86007553e-01,  2.40144423e-01,
        1.29383907e-01,  1.63847490e-01,  2.23652927e-01,  0.00000000e+00])

In [19]:
sol2 = np.linalg.lstsq(mat, rhs, rcond=None)[0]
sol2

array([-2.15114912e-01,  1.41649317e-01, -9.66755485e-02,  1.41649317e-01,
       -2.52871340e-01,  1.68445000e-01, -2.74272257e-01,  1.68445000e-01,
       -2.43747779e-01,  2.09306500e-01, -3.67882639e-01,  2.09306500e-01,
       -2.77134649e-01,  2.09306500e-01,  2.23716465e-01,  2.46268779e-01,
        9.81866440e-02,  2.46268779e-01, -3.82370735e-02,  2.46268779e-01,
        1.32683967e-01,  1.66910664e-01,  2.26952987e-01,  6.24500451e-17])

In [21]:
sol3 = np.linalg.inv(mat) @ rhs
sol3

array([ 5.31017265e-02,  8.43763359e-04,  1.85242027e-01,  8.43763359e-04,
       -1.36163481e+00,  4.58202618e-01, -1.00047513e+00,  4.58202618e-01,
       -2.39628959e-01,  2.07613982e-01, -3.62888864e-01,  2.07613982e-01,
       -2.72757028e-01,  2.07613982e-01,  2.28232867e-01,  2.40144423e-01,
        4.12466215e-01,  2.40144423e-01, -1.86007553e-01,  2.40144423e-01,
        1.29383907e-01,  1.63847490e-01,  2.23652927e-01,  0.00000000e+00])

In [18]:
# check:
mat @ sol1 - rhs

array([ 2.08166817e-17,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -1.71207509e-01,  0.00000000e+00, -9.71445147e-17,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -9.71445147e-17,  0.00000000e+00,
       -1.38777878e-17,  0.00000000e+00, -2.22044605e-16, -6.93889390e-18,
        1.23282837e+00, -6.93889390e-18, -4.18737700e-01,  2.08166817e-17,
        2.77555756e-17,  0.00000000e+00, -1.38777878e-17,  0.00000000e+00])

In [20]:
# check
mat @ sol2 - rhs

array([ 3.01841885e-16,  7.49400542e-16,  1.38777878e-17,  7.21644966e-16,
        1.66533454e-16,  2.22044605e-16,  2.08166817e-16,  3.88578059e-16,
        3.33066907e-16,  7.21644966e-16,  2.63677968e-16,  3.88578059e-16,
        2.63677968e-16,  7.21644966e-16,  1.11022302e-16,  4.09394740e-16,
        0.00000000e+00,  4.64905892e-16, -5.55111512e-17,  2.15105711e-16,
        3.60822483e-16, -8.04911693e-16,  2.08166817e-16,  6.24500451e-17])

In [24]:
# check
sol3 - sol1

array([-4.16333634e-17, -2.13587828e-17,  5.55111512e-17, -7.48099499e-18,
       -2.22044605e-16,  5.55111512e-17,  2.22044605e-16,  5.55111512e-17,
       -1.94289029e-16,  8.32667268e-17, -5.55111512e-17,  8.32667268e-17,
       -2.22044605e-16,  8.32667268e-17,  5.55111512e-17,  0.00000000e+00,
        5.55111512e-17,  0.00000000e+00,  0.00000000e+00, -2.77555756e-17,
        0.00000000e+00,  0.00000000e+00,  2.77555756e-17,  0.00000000e+00])

## Netlib

In [2]:
np.linalg.solve(mat, rhs)

array([-0.21511491,  0.14164932, -0.09667555,  0.14164932, -0.25287134,
        0.168445  , -0.27427226,  0.168445  , -0.24374778,  0.2093065 ,
       -0.36788264,  0.2093065 , -0.27713465,  0.2093065 ,  0.22371647,
        0.24626878,  0.09818664,  0.24626878, -0.03823707,  0.24626878,
        0.13268397,  0.16691066,  0.22695299,  0.        ])

In [3]:
np.linalg.lstsq(mat, rhs, rcond=None)[0]

array([-2.15114912e-01,  1.41649317e-01, -9.66755485e-02,  1.41649317e-01,
       -2.52871340e-01,  1.68445000e-01, -2.74272257e-01,  1.68445000e-01,
       -2.43747779e-01,  2.09306500e-01, -3.67882639e-01,  2.09306500e-01,
       -2.77134649e-01,  2.09306500e-01,  2.23716465e-01,  2.46268779e-01,
        9.81866440e-02,  2.46268779e-01, -3.82370735e-02,  2.46268779e-01,
        1.32683967e-01,  1.66910664e-01,  2.26952987e-01,  5.55111512e-17])

In [4]:
np.linalg.inv(mat) @ rhs

array([-0.21511491,  0.14164932, -0.09667555,  0.14164932, -0.25287134,
        0.168445  , -0.27427226,  0.168445  , -0.24374778,  0.2093065 ,
       -0.36788264,  0.2093065 , -0.27713465,  0.2093065 ,  0.22371647,
        0.24626878,  0.09818664,  0.24626878, -0.03823707,  0.24626878,
        0.13268397,  0.16691066,  0.22695299,  0.        ])

## MKL

In [2]:
np.linalg.solve(mat, rhs)

array([-0.21511491,  0.14164932, -0.09667555,  0.14164932, -0.25287134,
        0.168445  , -0.27427226,  0.168445  , -0.24374778,  0.2093065 ,
       -0.36788264,  0.2093065 , -0.27713465,  0.2093065 ,  0.22371647,
        0.24626878,  0.09818664,  0.24626878, -0.03823707,  0.24626878,
        0.13268397,  0.16691066,  0.22695299,  0.        ])

In [3]:
np.linalg.lstsq(mat, rhs, rcond=None)[0]

array([-2.15114912e-01,  1.41649317e-01, -9.66755485e-02,  1.41649317e-01,
       -2.52871340e-01,  1.68445000e-01, -2.74272257e-01,  1.68445000e-01,
       -2.43747779e-01,  2.09306500e-01, -3.67882639e-01,  2.09306500e-01,
       -2.77134649e-01,  2.09306500e-01,  2.23716465e-01,  2.46268779e-01,
        9.81866440e-02,  2.46268779e-01, -3.82370735e-02,  2.46268779e-01,
        1.32683967e-01,  1.66910664e-01,  2.26952987e-01,  1.07552856e-16])

In [4]:
np.linalg.inv(mat) @ rhs

array([-0.21511491,  0.14164932, -0.09667555,  0.14164932, -0.25287134,
        0.168445  , -0.27427226,  0.168445  , -0.24374778,  0.2093065 ,
       -0.36788264,  0.2093065 , -0.27713465,  0.2093065 ,  0.22371647,
        0.24626878,  0.09818664,  0.24626878, -0.03823707,  0.24626878,
        0.13268397,  0.16691066,  0.22695299,  0.        ])